/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduCourse;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 课程表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduCourseRecord extends UpdatableRecordImpl<EduCourseRecord> implements Record18<String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_course.id</code>. 课程ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_course.id</code>. 课程ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>lesson.edu_course.name</code>. 课程名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_course.name</code>. 课程名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lesson.edu_course.type</code>. 课程类型：PRIVATE-私教课，GROUP-团体课，ONLINE-线上课
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_course.type</code>. 课程类型：PRIVATE-私教课，GROUP-团体课，ONLINE-线上课
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.edu_course.status</code>. 状态：DRAFT-草稿，PUBLISHED-已发布，SUSPENDED-已暂停，TERMINATED-已终止
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_course.status</code>. 状态：DRAFT-草稿，PUBLISHED-已发布，SUSPENDED-已暂停，TERMINATED-已终止
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.edu_course.unit_hours</code>. 每次消耗课时数
     */
    public void setUnitHours(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_course.unit_hours</code>. 每次消耗课时数
     */
    public BigDecimal getUnitHours() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>lesson.edu_course.total_hours</code>. 总课时数
     */
    public void setTotalHours(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_course.total_hours</code>. 总课时数
     */
    public BigDecimal getTotalHours() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>lesson.edu_course.consumed_hours</code>. 已消耗课时数
     */
    public void setConsumedHours(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_course.consumed_hours</code>. 已消耗课时数
     */
    public BigDecimal getConsumedHours() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>lesson.edu_course.price</code>. 课程单价(元)
     */
    public void setPrice(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_course.price</code>. 课程单价(元)
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>lesson.edu_course.coach_id</code>. 上课教练ID
     */
    public void setCoachId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_course.coach_id</code>. 上课教练ID
     */
    public String getCoachId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>lesson.edu_course.coach_name</code>. 教练姓名
     */
    public void setCoachName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_course.coach_name</code>. 教练姓名
     */
    public String getCoachName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>lesson.edu_course.description</code>. 课程描述
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_course.description</code>. 课程描述
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>lesson.edu_course.campus_id</code>. 校区ID
     */
    public void setCampusId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.edu_course.campus_id</code>. 校区ID
     */
    public Long getCampusId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>lesson.edu_course.campus_name</code>. 校区名称
     */
    public void setCampusName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>lesson.edu_course.campus_name</code>. 校区名称
     */
    public String getCampusName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>lesson.edu_course.institution_id</code>. 机构ID
     */
    public void setInstitutionId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>lesson.edu_course.institution_id</code>. 机构ID
     */
    public Long getInstitutionId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>lesson.edu_course.institution_name</code>. 机构名称
     */
    public void setInstitutionName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>lesson.edu_course.institution_name</code>. 机构名称
     */
    public String getInstitutionName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>lesson.edu_course.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>lesson.edu_course.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>lesson.edu_course.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>lesson.edu_course.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>lesson.edu_course.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setDeleted(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>lesson.edu_course.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Integer getDeleted() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return EduCourse.EDU_COURSE.ID;
    }

    @Override
    public Field<String> field2() {
        return EduCourse.EDU_COURSE.NAME;
    }

    @Override
    public Field<String> field3() {
        return EduCourse.EDU_COURSE.TYPE;
    }

    @Override
    public Field<String> field4() {
        return EduCourse.EDU_COURSE.STATUS;
    }

    @Override
    public Field<BigDecimal> field5() {
        return EduCourse.EDU_COURSE.UNIT_HOURS;
    }

    @Override
    public Field<BigDecimal> field6() {
        return EduCourse.EDU_COURSE.TOTAL_HOURS;
    }

    @Override
    public Field<BigDecimal> field7() {
        return EduCourse.EDU_COURSE.CONSUMED_HOURS;
    }

    @Override
    public Field<BigDecimal> field8() {
        return EduCourse.EDU_COURSE.PRICE;
    }

    @Override
    public Field<String> field9() {
        return EduCourse.EDU_COURSE.COACH_ID;
    }

    @Override
    public Field<String> field10() {
        return EduCourse.EDU_COURSE.COACH_NAME;
    }

    @Override
    public Field<String> field11() {
        return EduCourse.EDU_COURSE.DESCRIPTION;
    }

    @Override
    public Field<Long> field12() {
        return EduCourse.EDU_COURSE.CAMPUS_ID;
    }

    @Override
    public Field<String> field13() {
        return EduCourse.EDU_COURSE.CAMPUS_NAME;
    }

    @Override
    public Field<Long> field14() {
        return EduCourse.EDU_COURSE.INSTITUTION_ID;
    }

    @Override
    public Field<String> field15() {
        return EduCourse.EDU_COURSE.INSTITUTION_NAME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return EduCourse.EDU_COURSE.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return EduCourse.EDU_COURSE.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field18() {
        return EduCourse.EDU_COURSE.DELETED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public BigDecimal component5() {
        return getUnitHours();
    }

    @Override
    public BigDecimal component6() {
        return getTotalHours();
    }

    @Override
    public BigDecimal component7() {
        return getConsumedHours();
    }

    @Override
    public BigDecimal component8() {
        return getPrice();
    }

    @Override
    public String component9() {
        return getCoachId();
    }

    @Override
    public String component10() {
        return getCoachName();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public Long component12() {
        return getCampusId();
    }

    @Override
    public String component13() {
        return getCampusName();
    }

    @Override
    public Long component14() {
        return getInstitutionId();
    }

    @Override
    public String component15() {
        return getInstitutionName();
    }

    @Override
    public LocalDateTime component16() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component17() {
        return getUpdateTime();
    }

    @Override
    public Integer component18() {
        return getDeleted();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public BigDecimal value5() {
        return getUnitHours();
    }

    @Override
    public BigDecimal value6() {
        return getTotalHours();
    }

    @Override
    public BigDecimal value7() {
        return getConsumedHours();
    }

    @Override
    public BigDecimal value8() {
        return getPrice();
    }

    @Override
    public String value9() {
        return getCoachId();
    }

    @Override
    public String value10() {
        return getCoachName();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public Long value12() {
        return getCampusId();
    }

    @Override
    public String value13() {
        return getCampusName();
    }

    @Override
    public Long value14() {
        return getInstitutionId();
    }

    @Override
    public String value15() {
        return getInstitutionName();
    }

    @Override
    public LocalDateTime value16() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value17() {
        return getUpdateTime();
    }

    @Override
    public Integer value18() {
        return getDeleted();
    }

    @Override
    public EduCourseRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public EduCourseRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public EduCourseRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public EduCourseRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public EduCourseRecord value5(BigDecimal value) {
        setUnitHours(value);
        return this;
    }

    @Override
    public EduCourseRecord value6(BigDecimal value) {
        setTotalHours(value);
        return this;
    }

    @Override
    public EduCourseRecord value7(BigDecimal value) {
        setConsumedHours(value);
        return this;
    }

    @Override
    public EduCourseRecord value8(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public EduCourseRecord value9(String value) {
        setCoachId(value);
        return this;
    }

    @Override
    public EduCourseRecord value10(String value) {
        setCoachName(value);
        return this;
    }

    @Override
    public EduCourseRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public EduCourseRecord value12(Long value) {
        setCampusId(value);
        return this;
    }

    @Override
    public EduCourseRecord value13(String value) {
        setCampusName(value);
        return this;
    }

    @Override
    public EduCourseRecord value14(Long value) {
        setInstitutionId(value);
        return this;
    }

    @Override
    public EduCourseRecord value15(String value) {
        setInstitutionName(value);
        return this;
    }

    @Override
    public EduCourseRecord value16(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public EduCourseRecord value17(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public EduCourseRecord value18(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public EduCourseRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, String value9, String value10, String value11, Long value12, String value13, Long value14, String value15, LocalDateTime value16, LocalDateTime value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduCourseRecord
     */
    public EduCourseRecord() {
        super(EduCourse.EDU_COURSE);
    }

    /**
     * Create a detached, initialised EduCourseRecord
     */
    public EduCourseRecord(String id, String name, String type, String status, BigDecimal unitHours, BigDecimal totalHours, BigDecimal consumedHours, BigDecimal price, String coachId, String coachName, String description, Long campusId, String campusName, Long institutionId, String institutionName, LocalDateTime createdTime, LocalDateTime updateTime, Integer deleted) {
        super(EduCourse.EDU_COURSE);

        setId(id);
        setName(name);
        setType(type);
        setStatus(status);
        setUnitHours(unitHours);
        setTotalHours(totalHours);
        setConsumedHours(consumedHours);
        setPrice(price);
        setCoachId(coachId);
        setCoachName(coachName);
        setDescription(description);
        setCampusId(campusId);
        setCampusName(campusName);
        setInstitutionId(institutionId);
        setInstitutionName(institutionName);
        setCreatedTime(createdTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
    }
}
