/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduCourseCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 课程分类表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduCourseCategoryRecord extends UpdatableRecordImpl<EduCourseCategoryRecord> implements Record12<Long, Long, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_course_category.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.edu_course_category.parent_id</code>. 父分类ID
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.parent_id</code>. 父分类ID
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson.edu_course_category.name</code>. 分类名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.name</code>. 分类名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.edu_course_category.code</code>. 分类编码
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.code</code>. 分类编码
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.edu_course_category.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.edu_course_category.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lesson.edu_course_category.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>lesson.edu_course_category.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>lesson.edu_course_category.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>lesson.edu_course_category.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.edu_course_category.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>lesson.edu_course_category.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.edu_course_category.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.PARENT_ID;
    }

    @Override
    public Field<String> field3() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.NAME;
    }

    @Override
    public Field<String> field4() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.CODE;
    }

    @Override
    public Field<String> field5() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.ICON;
    }

    @Override
    public Field<Integer> field6() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.SORT;
    }

    @Override
    public Field<Byte> field7() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.STATUS;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.UPDATED_AT;
    }

    @Override
    public Field<Long> field10() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.CREATED_BY;
    }

    @Override
    public Field<Long> field11() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.UPDATED_BY;
    }

    @Override
    public Field<Byte> field12() {
        return EduCourseCategory.EDU_COURSE_CATEGORY.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getParentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getCode();
    }

    @Override
    public String component5() {
        return getIcon();
    }

    @Override
    public Integer component6() {
        return getSort();
    }

    @Override
    public Byte component7() {
        return getStatus();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public Long component10() {
        return getCreatedBy();
    }

    @Override
    public Long component11() {
        return getUpdatedBy();
    }

    @Override
    public Byte component12() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getParentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getCode();
    }

    @Override
    public String value5() {
        return getIcon();
    }

    @Override
    public Integer value6() {
        return getSort();
    }

    @Override
    public Byte value7() {
        return getStatus();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public Long value10() {
        return getCreatedBy();
    }

    @Override
    public Long value11() {
        return getUpdatedBy();
    }

    @Override
    public Byte value12() {
        return getIsDeleted();
    }

    @Override
    public EduCourseCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value2(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value4(String value) {
        setCode(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value5(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value6(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value10(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value11(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord value12(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public EduCourseCategoryRecord values(Long value1, Long value2, String value3, String value4, String value5, Integer value6, Byte value7, LocalDateTime value8, LocalDateTime value9, Long value10, Long value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduCourseCategoryRecord
     */
    public EduCourseCategoryRecord() {
        super(EduCourseCategory.EDU_COURSE_CATEGORY);
    }

    /**
     * Create a detached, initialised EduCourseCategoryRecord
     */
    public EduCourseCategoryRecord(Long id, Long parentId, String name, String code, String icon, Integer sort, Byte status, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(EduCourseCategory.EDU_COURSE_CATEGORY);

        setId(id);
        setParentId(parentId);
        setName(name);
        setCode(code);
        setIcon(icon);
        setSort(sort);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
