/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduCourseLesson;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 课程课时表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduCourseLessonRecord extends UpdatableRecordImpl<EduCourseLessonRecord> implements Record14<Long, Long, Long, String, String, Integer, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_course_lesson.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.course_id</code>. 课程ID
     */
    public void setCourseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.course_id</code>. 课程ID
     */
    public Long getCourseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.chapter_id</code>. 章节ID
     */
    public void setChapterId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.chapter_id</code>. 章节ID
     */
    public Long getChapterId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.name</code>. 课时名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.name</code>. 课时名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.description</code>. 课时描述
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.description</code>. 课时描述
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.duration</code>. 课时时长(分钟)
     */
    public void setDuration(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.duration</code>. 课时时长(分钟)
     */
    public Integer getDuration() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.video_url</code>. 视频URL
     */
    public void setVideoUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.video_url</code>. 视频URL
     */
    public String getVideoUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>lesson.edu_course_lesson.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>lesson.edu_course_lesson.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, Long, String, String, Integer, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, Long, Long, String, String, Integer, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduCourseLesson.EDU_COURSE_LESSON.ID;
    }

    @Override
    public Field<Long> field2() {
        return EduCourseLesson.EDU_COURSE_LESSON.COURSE_ID;
    }

    @Override
    public Field<Long> field3() {
        return EduCourseLesson.EDU_COURSE_LESSON.CHAPTER_ID;
    }

    @Override
    public Field<String> field4() {
        return EduCourseLesson.EDU_COURSE_LESSON.NAME;
    }

    @Override
    public Field<String> field5() {
        return EduCourseLesson.EDU_COURSE_LESSON.DESCRIPTION;
    }

    @Override
    public Field<Integer> field6() {
        return EduCourseLesson.EDU_COURSE_LESSON.DURATION;
    }

    @Override
    public Field<String> field7() {
        return EduCourseLesson.EDU_COURSE_LESSON.VIDEO_URL;
    }

    @Override
    public Field<Integer> field8() {
        return EduCourseLesson.EDU_COURSE_LESSON.SORT;
    }

    @Override
    public Field<Byte> field9() {
        return EduCourseLesson.EDU_COURSE_LESSON.STATUS;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return EduCourseLesson.EDU_COURSE_LESSON.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return EduCourseLesson.EDU_COURSE_LESSON.UPDATED_AT;
    }

    @Override
    public Field<Long> field12() {
        return EduCourseLesson.EDU_COURSE_LESSON.CREATED_BY;
    }

    @Override
    public Field<Long> field13() {
        return EduCourseLesson.EDU_COURSE_LESSON.UPDATED_BY;
    }

    @Override
    public Field<Byte> field14() {
        return EduCourseLesson.EDU_COURSE_LESSON.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCourseId();
    }

    @Override
    public Long component3() {
        return getChapterId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer component6() {
        return getDuration();
    }

    @Override
    public String component7() {
        return getVideoUrl();
    }

    @Override
    public Integer component8() {
        return getSort();
    }

    @Override
    public Byte component9() {
        return getStatus();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public Long component12() {
        return getCreatedBy();
    }

    @Override
    public Long component13() {
        return getUpdatedBy();
    }

    @Override
    public Byte component14() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCourseId();
    }

    @Override
    public Long value3() {
        return getChapterId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Integer value6() {
        return getDuration();
    }

    @Override
    public String value7() {
        return getVideoUrl();
    }

    @Override
    public Integer value8() {
        return getSort();
    }

    @Override
    public Byte value9() {
        return getStatus();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public Long value12() {
        return getCreatedBy();
    }

    @Override
    public Long value13() {
        return getUpdatedBy();
    }

    @Override
    public Byte value14() {
        return getIsDeleted();
    }

    @Override
    public EduCourseLessonRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value2(Long value) {
        setCourseId(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value3(Long value) {
        setChapterId(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value6(Integer value) {
        setDuration(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value7(String value) {
        setVideoUrl(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value8(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value11(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value12(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value13(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord value14(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public EduCourseLessonRecord values(Long value1, Long value2, Long value3, String value4, String value5, Integer value6, String value7, Integer value8, Byte value9, LocalDateTime value10, LocalDateTime value11, Long value12, Long value13, Byte value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduCourseLessonRecord
     */
    public EduCourseLessonRecord() {
        super(EduCourseLesson.EDU_COURSE_LESSON);
    }

    /**
     * Create a detached, initialised EduCourseLessonRecord
     */
    public EduCourseLessonRecord(Long id, Long courseId, Long chapterId, String name, String description, Integer duration, String videoUrl, Integer sort, Byte status, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(EduCourseLesson.EDU_COURSE_LESSON);

        setId(id);
        setCourseId(courseId);
        setChapterId(chapterId);
        setName(name);
        setDescription(description);
        setDuration(duration);
        setVideoUrl(videoUrl);
        setSort(sort);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
