/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduCourseChapter;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 课程章节表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduCourseChapterRecord extends UpdatableRecordImpl<EduCourseChapterRecord> implements Record11<Long, Long, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_course_chapter.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.course_id</code>. 课程ID
     */
    public void setCourseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.course_id</code>. 课程ID
     */
    public Long getCourseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.name</code>. 章节名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.name</code>. 章节名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.description</code>. 章节描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.description</code>. 章节描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.edu_course_chapter.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_course_chapter.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.ID;
    }

    @Override
    public Field<Long> field2() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.COURSE_ID;
    }

    @Override
    public Field<String> field3() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.NAME;
    }

    @Override
    public Field<String> field4() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.DESCRIPTION;
    }

    @Override
    public Field<Integer> field5() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.SORT;
    }

    @Override
    public Field<Byte> field6() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.UPDATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.CREATED_BY;
    }

    @Override
    public Field<Long> field10() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.UPDATED_BY;
    }

    @Override
    public Field<Byte> field11() {
        return EduCourseChapter.EDU_COURSE_CHAPTER.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCourseId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Integer component5() {
        return getSort();
    }

    @Override
    public Byte component6() {
        return getStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Long component9() {
        return getCreatedBy();
    }

    @Override
    public Long component10() {
        return getUpdatedBy();
    }

    @Override
    public Byte component11() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCourseId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Integer value5() {
        return getSort();
    }

    @Override
    public Byte value6() {
        return getStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public Long value9() {
        return getCreatedBy();
    }

    @Override
    public Long value10() {
        return getUpdatedBy();
    }

    @Override
    public Byte value11() {
        return getIsDeleted();
    }

    @Override
    public EduCourseChapterRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value2(Long value) {
        setCourseId(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value5(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value9(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value10(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord value11(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public EduCourseChapterRecord values(Long value1, Long value2, String value3, String value4, Integer value5, Byte value6, LocalDateTime value7, LocalDateTime value8, Long value9, Long value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduCourseChapterRecord
     */
    public EduCourseChapterRecord() {
        super(EduCourseChapter.EDU_COURSE_CHAPTER);
    }

    /**
     * Create a detached, initialised EduCourseChapterRecord
     */
    public EduCourseChapterRecord(Long id, Long courseId, String name, String description, Integer sort, Byte status, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(EduCourseChapter.EDU_COURSE_CHAPTER);

        setId(id);
        setCourseId(courseId);
        setName(name);
        setDescription(description);
        setSort(sort);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
