/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduStudentClassTransfer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学员转班记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduStudentClassTransferRecord extends UpdatableRecordImpl<EduStudentClassTransferRecord> implements Record14<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_student_class_transfer.id</code>. 记录ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.id</code>. 记录ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.student_id</code>. 学员ID
     */
    public void setStudentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.student_id</code>. 学员ID
     */
    public String getStudentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.course_id</code>. 课程ID
     */
    public void setCourseId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.course_id</code>. 课程ID
     */
    public String getCourseId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.course_name</code>. 课程名称
     */
    public void setCourseName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.course_name</code>. 课程名称
     */
    public String getCourseName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.original_schedule</code>. 原上课时间
     */
    public void setOriginalSchedule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.original_schedule</code>. 原上课时间
     */
    public String getOriginalSchedule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.new_schedule</code>. 新上课时间
     */
    public void setNewSchedule(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.new_schedule</code>. 新上课时间
     */
    public String getNewSchedule() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.reason</code>. 转班原因
     */
    public void setReason(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.reason</code>. 转班原因
     */
    public String getReason() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.campus_id</code>. 校区ID
     */
    public void setCampusId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.campus_id</code>. 校区ID
     */
    public Long getCampusId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.campus_name</code>. 校区名称
     */
    public void setCampusName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.campus_name</code>. 校区名称
     */
    public String getCampusName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.institution_id</code>. 机构ID
     */
    public void setInstitutionId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.institution_id</code>. 机构ID
     */
    public Long getInstitutionId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.institution_name</code>. 机构名称
     */
    public void setInstitutionName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.institution_name</code>. 机构名称
     */
    public String getInstitutionName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>lesson.edu_student_class_transfer.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setDeleted(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>lesson.edu_student_class_transfer.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Integer getDeleted() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, Long, String, Long, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.ID;
    }

    @Override
    public Field<String> field2() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.STUDENT_ID;
    }

    @Override
    public Field<String> field3() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.COURSE_ID;
    }

    @Override
    public Field<String> field4() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.COURSE_NAME;
    }

    @Override
    public Field<String> field5() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.ORIGINAL_SCHEDULE;
    }

    @Override
    public Field<String> field6() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.NEW_SCHEDULE;
    }

    @Override
    public Field<String> field7() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.REASON;
    }

    @Override
    public Field<Long> field8() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.CAMPUS_ID;
    }

    @Override
    public Field<String> field9() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.CAMPUS_NAME;
    }

    @Override
    public Field<Long> field10() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.INSTITUTION_ID;
    }

    @Override
    public Field<String> field11() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.INSTITUTION_NAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field14() {
        return EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStudentId();
    }

    @Override
    public String component3() {
        return getCourseId();
    }

    @Override
    public String component4() {
        return getCourseName();
    }

    @Override
    public String component5() {
        return getOriginalSchedule();
    }

    @Override
    public String component6() {
        return getNewSchedule();
    }

    @Override
    public String component7() {
        return getReason();
    }

    @Override
    public Long component8() {
        return getCampusId();
    }

    @Override
    public String component9() {
        return getCampusName();
    }

    @Override
    public Long component10() {
        return getInstitutionId();
    }

    @Override
    public String component11() {
        return getInstitutionName();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdateTime();
    }

    @Override
    public Integer component14() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStudentId();
    }

    @Override
    public String value3() {
        return getCourseId();
    }

    @Override
    public String value4() {
        return getCourseName();
    }

    @Override
    public String value5() {
        return getOriginalSchedule();
    }

    @Override
    public String value6() {
        return getNewSchedule();
    }

    @Override
    public String value7() {
        return getReason();
    }

    @Override
    public Long value8() {
        return getCampusId();
    }

    @Override
    public String value9() {
        return getCampusName();
    }

    @Override
    public Long value10() {
        return getInstitutionId();
    }

    @Override
    public String value11() {
        return getInstitutionName();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdateTime();
    }

    @Override
    public Integer value14() {
        return getDeleted();
    }

    @Override
    public EduStudentClassTransferRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value2(String value) {
        setStudentId(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value3(String value) {
        setCourseId(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value4(String value) {
        setCourseName(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value5(String value) {
        setOriginalSchedule(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value6(String value) {
        setNewSchedule(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value7(String value) {
        setReason(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value8(Long value) {
        setCampusId(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value9(String value) {
        setCampusName(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value10(Long value) {
        setInstitutionId(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value11(String value) {
        setInstitutionName(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value12(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value13(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord value14(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public EduStudentClassTransferRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, String value9, Long value10, String value11, LocalDateTime value12, LocalDateTime value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduStudentClassTransferRecord
     */
    public EduStudentClassTransferRecord() {
        super(EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER);
    }

    /**
     * Create a detached, initialised EduStudentClassTransferRecord
     */
    public EduStudentClassTransferRecord(Long id, String studentId, String courseId, String courseName, String originalSchedule, String newSchedule, String reason, Long campusId, String campusName, Long institutionId, String institutionName, LocalDateTime createdTime, LocalDateTime updateTime, Integer deleted) {
        super(EduStudentClassTransfer.EDU_STUDENT_CLASS_TRANSFER);

        setId(id);
        setStudentId(studentId);
        setCourseId(courseId);
        setCourseName(courseName);
        setOriginalSchedule(originalSchedule);
        setNewSchedule(newSchedule);
        setReason(reason);
        setCampusId(campusId);
        setCampusName(campusName);
        setInstitutionId(institutionId);
        setInstitutionName(institutionName);
        setCreatedTime(createdTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
    }
}
