/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.EduStudentCourseOperationRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学生课程操作记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduStudentCourseOperationRecordRecord extends UpdatableRecordImpl<EduStudentCourseOperationRecordRecord> implements Record21<Long, Long, String, Long, String, String, String, String, Long, Long, Long, Long, BigDecimal, String, String, Long, String, LocalDateTime, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.id</code>. 记录ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.id</code>. 记录ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.student_id</code>. 学生ID
     */
    public void setStudentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.student_id</code>. 学生ID
     */
    public Long getStudentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.student_name</code>. 学生姓名
     */
    public void setStudentName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.student_name</code>. 学生姓名
     */
    public String getStudentName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.course_id</code>. 课程ID
     */
    public void setCourseId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.course_id</code>. 课程ID
     */
    public Long getCourseId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.course_name</code>. 课程名称
     */
    public void setCourseName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.course_name</code>. 课程名称
     */
    public String getCourseName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.operation_type</code>. 操作类型：TRANSFER_COURSE-转课, TRANSFER_CLASS-转班, REFUND-退费
     */
    public void setOperationType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.operation_type</code>. 操作类型：TRANSFER_COURSE-转课, TRANSFER_CLASS-转班, REFUND-退费
     */
    public String getOperationType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.before_status</code>. 操作前状态
     */
    public void setBeforeStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.before_status</code>. 操作前状态
     */
    public String getBeforeStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.after_status</code>. 操作后状态
     */
    public void setAfterStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.after_status</code>. 操作后状态
     */
    public String getAfterStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.source_course_id</code>. 原课程ID（转课时使用）
     */
    public void setSourceCourseId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.source_course_id</code>. 原课程ID（转课时使用）
     */
    public Long getSourceCourseId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.target_course_id</code>. 目标课程ID（转课时使用）
     */
    public void setTargetCourseId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.target_course_id</code>. 目标课程ID（转课时使用）
     */
    public Long getTargetCourseId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.source_class_id</code>. 原班级ID（转班时使用）
     */
    public void setSourceClassId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.source_class_id</code>. 原班级ID（转班时使用）
     */
    public Long getSourceClassId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.target_class_id</code>. 目标班级ID（转班时使用）
     */
    public void setTargetClassId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.target_class_id</code>. 目标班级ID（转班时使用）
     */
    public Long getTargetClassId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.refund_amount</code>. 退费金额（退费时使用）
     */
    public void setRefundAmount(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.refund_amount</code>. 退费金额（退费时使用）
     */
    public BigDecimal getRefundAmount() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.refund_method</code>. 退费方式：CASH-现金, BANK_TRANSFER-银行转账, WECHAT-微信, ALIPAY-支付宝
     */
    public void setRefundMethod(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.refund_method</code>. 退费方式：CASH-现金, BANK_TRANSFER-银行转账, WECHAT-微信, ALIPAY-支付宝
     */
    public String getRefundMethod() {
        return (String) get(13);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.operation_reason</code>. 操作原因
     */
    public void setOperationReason(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.operation_reason</code>. 操作原因
     */
    public String getOperationReason() {
        return (String) get(14);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.operator_id</code>. 操作人ID
     */
    public void setOperatorId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.operator_id</code>. 操作人ID
     */
    public Long getOperatorId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.operator_name</code>. 操作人姓名
     */
    public void setOperatorName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.operator_name</code>. 操作人姓名
     */
    public String getOperatorName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.operation_time</code>. 操作时间
     */
    public void setOperationTime(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.operation_time</code>. 操作时间
     */
    public LocalDateTime getOperationTime() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setDeleted(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>lesson.edu_student_course_operation_record.updated_time</code>. 更新时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>lesson.edu_student_course_operation_record.updated_time</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Long, Long, String, Long, String, String, String, String, Long, Long, Long, Long, BigDecimal, String, String, Long, String, LocalDateTime, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Long, Long, String, Long, String, String, String, String, Long, Long, Long, Long, BigDecimal, String, String, Long, String, LocalDateTime, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.ID;
    }

    @Override
    public Field<Long> field2() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.STUDENT_ID;
    }

    @Override
    public Field<String> field3() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.STUDENT_NAME;
    }

    @Override
    public Field<Long> field4() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.COURSE_ID;
    }

    @Override
    public Field<String> field5() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.COURSE_NAME;
    }

    @Override
    public Field<String> field6() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.OPERATION_TYPE;
    }

    @Override
    public Field<String> field7() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.BEFORE_STATUS;
    }

    @Override
    public Field<String> field8() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.AFTER_STATUS;
    }

    @Override
    public Field<Long> field9() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.SOURCE_COURSE_ID;
    }

    @Override
    public Field<Long> field10() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.TARGET_COURSE_ID;
    }

    @Override
    public Field<Long> field11() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.SOURCE_CLASS_ID;
    }

    @Override
    public Field<Long> field12() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.TARGET_CLASS_ID;
    }

    @Override
    public Field<BigDecimal> field13() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.REFUND_AMOUNT;
    }

    @Override
    public Field<String> field14() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.REFUND_METHOD;
    }

    @Override
    public Field<String> field15() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.OPERATION_REASON;
    }

    @Override
    public Field<Long> field16() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.OPERATOR_ID;
    }

    @Override
    public Field<String> field17() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.OPERATOR_NAME;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.OPERATION_TIME;
    }

    @Override
    public Field<Byte> field19() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.DELETED;
    }

    @Override
    public Field<LocalDateTime> field20() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD.UPDATED_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getStudentId();
    }

    @Override
    public String component3() {
        return getStudentName();
    }

    @Override
    public Long component4() {
        return getCourseId();
    }

    @Override
    public String component5() {
        return getCourseName();
    }

    @Override
    public String component6() {
        return getOperationType();
    }

    @Override
    public String component7() {
        return getBeforeStatus();
    }

    @Override
    public String component8() {
        return getAfterStatus();
    }

    @Override
    public Long component9() {
        return getSourceCourseId();
    }

    @Override
    public Long component10() {
        return getTargetCourseId();
    }

    @Override
    public Long component11() {
        return getSourceClassId();
    }

    @Override
    public Long component12() {
        return getTargetClassId();
    }

    @Override
    public BigDecimal component13() {
        return getRefundAmount();
    }

    @Override
    public String component14() {
        return getRefundMethod();
    }

    @Override
    public String component15() {
        return getOperationReason();
    }

    @Override
    public Long component16() {
        return getOperatorId();
    }

    @Override
    public String component17() {
        return getOperatorName();
    }

    @Override
    public LocalDateTime component18() {
        return getOperationTime();
    }

    @Override
    public Byte component19() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component20() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component21() {
        return getUpdatedTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getStudentId();
    }

    @Override
    public String value3() {
        return getStudentName();
    }

    @Override
    public Long value4() {
        return getCourseId();
    }

    @Override
    public String value5() {
        return getCourseName();
    }

    @Override
    public String value6() {
        return getOperationType();
    }

    @Override
    public String value7() {
        return getBeforeStatus();
    }

    @Override
    public String value8() {
        return getAfterStatus();
    }

    @Override
    public Long value9() {
        return getSourceCourseId();
    }

    @Override
    public Long value10() {
        return getTargetCourseId();
    }

    @Override
    public Long value11() {
        return getSourceClassId();
    }

    @Override
    public Long value12() {
        return getTargetClassId();
    }

    @Override
    public BigDecimal value13() {
        return getRefundAmount();
    }

    @Override
    public String value14() {
        return getRefundMethod();
    }

    @Override
    public String value15() {
        return getOperationReason();
    }

    @Override
    public Long value16() {
        return getOperatorId();
    }

    @Override
    public String value17() {
        return getOperatorName();
    }

    @Override
    public LocalDateTime value18() {
        return getOperationTime();
    }

    @Override
    public Byte value19() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value20() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value21() {
        return getUpdatedTime();
    }

    @Override
    public EduStudentCourseOperationRecordRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value2(Long value) {
        setStudentId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value3(String value) {
        setStudentName(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value4(Long value) {
        setCourseId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value5(String value) {
        setCourseName(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value6(String value) {
        setOperationType(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value7(String value) {
        setBeforeStatus(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value8(String value) {
        setAfterStatus(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value9(Long value) {
        setSourceCourseId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value10(Long value) {
        setTargetCourseId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value11(Long value) {
        setSourceClassId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value12(Long value) {
        setTargetClassId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value13(BigDecimal value) {
        setRefundAmount(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value14(String value) {
        setRefundMethod(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value15(String value) {
        setOperationReason(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value16(Long value) {
        setOperatorId(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value17(String value) {
        setOperatorName(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value18(LocalDateTime value) {
        setOperationTime(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value19(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value20(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord value21(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public EduStudentCourseOperationRecordRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, String value7, String value8, Long value9, Long value10, Long value11, Long value12, BigDecimal value13, String value14, String value15, Long value16, String value17, LocalDateTime value18, Byte value19, LocalDateTime value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduStudentCourseOperationRecordRecord
     */
    public EduStudentCourseOperationRecordRecord() {
        super(EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD);
    }

    /**
     * Create a detached, initialised EduStudentCourseOperationRecordRecord
     */
    public EduStudentCourseOperationRecordRecord(Long id, Long studentId, String studentName, Long courseId, String courseName, String operationType, String beforeStatus, String afterStatus, Long sourceCourseId, Long targetCourseId, Long sourceClassId, Long targetClassId, BigDecimal refundAmount, String refundMethod, String operationReason, Long operatorId, String operatorName, LocalDateTime operationTime, Byte deleted, LocalDateTime createdTime, LocalDateTime updatedTime) {
        super(EduStudentCourseOperationRecord.EDU_STUDENT_COURSE_OPERATION_RECORD);

        setId(id);
        setStudentId(studentId);
        setStudentName(studentName);
        setCourseId(courseId);
        setCourseName(courseName);
        setOperationType(operationType);
        setBeforeStatus(beforeStatus);
        setAfterStatus(afterStatus);
        setSourceCourseId(sourceCourseId);
        setTargetCourseId(targetCourseId);
        setSourceClassId(sourceClassId);
        setTargetClassId(targetClassId);
        setRefundAmount(refundAmount);
        setRefundMethod(refundMethod);
        setOperationReason(operationReason);
        setOperatorId(operatorId);
        setOperatorName(operatorName);
        setOperationTime(operationTime);
        setDeleted(deleted);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
    }
}
