package com.lesson.repository.tables.records;

import com.lesson.repository.tables.EduUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduUserRecord extends UpdatableRecordImpl<EduUserRecord> implements Record8<Long, String, String, String, String, String, Byte, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>edu_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>edu_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>edu_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>edu_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>edu_user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>edu_user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>edu_user.real_name</code>.
     */
    public void setRealName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>edu_user.real_name</code>.
     */
    public String getRealName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edu_user.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>edu_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>edu_user.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>edu_user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>edu_user.status</code>.
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>edu_user.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>edu_user.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>edu_user.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, String, Byte, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, String, String, String, Byte, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EduUser.EDU_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return EduUser.EDU_USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return EduUser.EDU_USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return EduUser.EDU_USER.REAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return EduUser.EDU_USER.PHONE;
    }

    @Override
    public Field<String> field6() {
        return EduUser.EDU_USER.EMAIL;
    }

    @Override
    public Field<Byte> field7() {
        return EduUser.EDU_USER.STATUS;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return EduUser.EDU_USER.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getRealName();
    }

    @Override
    public String component5() {
        return getPhone();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public Byte component7() {
        return getStatus();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getRealName();
    }

    @Override
    public String value5() {
        return getPhone();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public Byte value7() {
        return getStatus();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public EduUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EduUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public EduUserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public EduUserRecord value4(String value) {
        setRealName(value);
        return this;
    }

    @Override
    public EduUserRecord value5(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public EduUserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EduUserRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public EduUserRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EduUserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Byte value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EduUserRecord
     */
    public EduUserRecord() {
        super(EduUser.EDU_USER);
    }

    /**
     * Create a detached, initialised EduUserRecord
     */
    public EduUserRecord(Long id, String username, String password, String realName, String phone, String email, Byte status, LocalDateTime createdAt) {
        super(EduUser.EDU_USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setRealName(realName);
        setPhone(phone);
        setEmail(email);
        setStatus(status);
        setCreatedAt(createdAt);
    }
} 