/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.SysConfig;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysConfigRecord extends UpdatableRecordImpl<SysConfigRecord> implements Record11<Long, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.sys_config.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.sys_config.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.sys_config.config_key</code>. 配置键
     */
    public void setConfigKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.sys_config.config_key</code>. 配置键
     */
    public String getConfigKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lesson.sys_config.config_value</code>. 配置值
     */
    public void setConfigValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.sys_config.config_value</code>. 配置值
     */
    public String getConfigValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.sys_config.config_type</code>. 配置类型
     */
    public void setConfigType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.sys_config.config_type</code>. 配置类型
     */
    public String getConfigType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.sys_config.description</code>. 描述
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.sys_config.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.sys_config.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.sys_config.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>lesson.sys_config.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.sys_config.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>lesson.sys_config.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.sys_config.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>lesson.sys_config.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.sys_config.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>lesson.sys_config.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.sys_config.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.sys_config.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.sys_config.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysConfig.SYS_CONFIG.ID;
    }

    @Override
    public Field<String> field2() {
        return SysConfig.SYS_CONFIG.CONFIG_KEY;
    }

    @Override
    public Field<String> field3() {
        return SysConfig.SYS_CONFIG.CONFIG_VALUE;
    }

    @Override
    public Field<String> field4() {
        return SysConfig.SYS_CONFIG.CONFIG_TYPE;
    }

    @Override
    public Field<String> field5() {
        return SysConfig.SYS_CONFIG.DESCRIPTION;
    }

    @Override
    public Field<Byte> field6() {
        return SysConfig.SYS_CONFIG.STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SysConfig.SYS_CONFIG.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return SysConfig.SYS_CONFIG.UPDATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return SysConfig.SYS_CONFIG.CREATED_BY;
    }

    @Override
    public Field<Long> field10() {
        return SysConfig.SYS_CONFIG.UPDATED_BY;
    }

    @Override
    public Field<Byte> field11() {
        return SysConfig.SYS_CONFIG.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getConfigKey();
    }

    @Override
    public String component3() {
        return getConfigValue();
    }

    @Override
    public String component4() {
        return getConfigType();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Byte component6() {
        return getStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Long component9() {
        return getCreatedBy();
    }

    @Override
    public Long component10() {
        return getUpdatedBy();
    }

    @Override
    public Byte component11() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getConfigKey();
    }

    @Override
    public String value3() {
        return getConfigValue();
    }

    @Override
    public String value4() {
        return getConfigType();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Byte value6() {
        return getStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public Long value9() {
        return getCreatedBy();
    }

    @Override
    public Long value10() {
        return getUpdatedBy();
    }

    @Override
    public Byte value11() {
        return getIsDeleted();
    }

    @Override
    public SysConfigRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysConfigRecord value2(String value) {
        setConfigKey(value);
        return this;
    }

    @Override
    public SysConfigRecord value3(String value) {
        setConfigValue(value);
        return this;
    }

    @Override
    public SysConfigRecord value4(String value) {
        setConfigType(value);
        return this;
    }

    @Override
    public SysConfigRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SysConfigRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysConfigRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SysConfigRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SysConfigRecord value9(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SysConfigRecord value10(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public SysConfigRecord value11(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SysConfigRecord values(Long value1, String value2, String value3, String value4, String value5, Byte value6, LocalDateTime value7, LocalDateTime value8, Long value9, Long value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysConfigRecord
     */
    public SysConfigRecord() {
        super(SysConfig.SYS_CONFIG);
    }

    /**
     * Create a detached, initialised SysConfigRecord
     */
    public SysConfigRecord(Long id, String configKey, String configValue, String configType, String description, Byte status, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(SysConfig.SYS_CONFIG);

        setId(id);
        setConfigKey(configKey);
        setConfigValue(configValue);
        setConfigType(configType);
        setDescription(description);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
