/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.SysDictType;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 字典类型表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictTypeRecord extends UpdatableRecordImpl<SysDictTypeRecord> implements Record10<Long, String, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.sys_dict_type.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.dict_name</code>. 字典名称
     */
    public void setDictName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.dict_name</code>. 字典名称
     */
    public String getDictName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.dict_type</code>. 字典类型
     */
    public void setDictType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.dict_type</code>. 字典类型
     */
    public String getDictType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>lesson.sys_dict_type.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.sys_dict_type.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysDictType.SYS_DICT_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return SysDictType.SYS_DICT_TYPE.DICT_NAME;
    }

    @Override
    public Field<String> field3() {
        return SysDictType.SYS_DICT_TYPE.DICT_TYPE;
    }

    @Override
    public Field<Byte> field4() {
        return SysDictType.SYS_DICT_TYPE.STATUS;
    }

    @Override
    public Field<String> field5() {
        return SysDictType.SYS_DICT_TYPE.REMARK;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SysDictType.SYS_DICT_TYPE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SysDictType.SYS_DICT_TYPE.UPDATED_AT;
    }

    @Override
    public Field<Long> field8() {
        return SysDictType.SYS_DICT_TYPE.CREATED_BY;
    }

    @Override
    public Field<Long> field9() {
        return SysDictType.SYS_DICT_TYPE.UPDATED_BY;
    }

    @Override
    public Field<Byte> field10() {
        return SysDictType.SYS_DICT_TYPE.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDictName();
    }

    @Override
    public String component3() {
        return getDictType();
    }

    @Override
    public Byte component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getRemark();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public Long component8() {
        return getCreatedBy();
    }

    @Override
    public Long component9() {
        return getUpdatedBy();
    }

    @Override
    public Byte component10() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDictName();
    }

    @Override
    public String value3() {
        return getDictType();
    }

    @Override
    public Byte value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getRemark();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public Long value8() {
        return getCreatedBy();
    }

    @Override
    public Long value9() {
        return getUpdatedBy();
    }

    @Override
    public Byte value10() {
        return getIsDeleted();
    }

    @Override
    public SysDictTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value2(String value) {
        setDictName(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value3(String value) {
        setDictType(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value4(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value5(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value8(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value9(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public SysDictTypeRecord value10(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SysDictTypeRecord values(Long value1, String value2, String value3, Byte value4, String value5, LocalDateTime value6, LocalDateTime value7, Long value8, Long value9, Byte value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysDictTypeRecord
     */
    public SysDictTypeRecord() {
        super(SysDictType.SYS_DICT_TYPE);
    }

    /**
     * Create a detached, initialised SysDictTypeRecord
     */
    public SysDictTypeRecord(Long id, String dictName, String dictType, Byte status, String remark, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(SysDictType.SYS_DICT_TYPE);

        setId(id);
        setDictName(dictName);
        setDictType(dictType);
        setStatus(status);
        setRemark(remark);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
