/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.SysNotice;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知公告表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysNoticeRecord extends UpdatableRecordImpl<SysNoticeRecord> implements Record11<Long, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.sys_notice.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.sys_notice.notice_title</code>. 公告标题
     */
    public void setNoticeTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.notice_title</code>. 公告标题
     */
    public String getNoticeTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lesson.sys_notice.notice_type</code>. 公告类型：1-通知，2-公告
     */
    public void setNoticeType(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.notice_type</code>. 公告类型：1-通知，2-公告
     */
    public Byte getNoticeType() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>lesson.sys_notice.notice_content</code>. 公告内容
     */
    public void setNoticeContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.notice_content</code>. 公告内容
     */
    public String getNoticeContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lesson.sys_notice.status</code>. 状态：0-关闭，1-正常
     */
    public void setStatus(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.status</code>. 状态：0-关闭，1-正常
     */
    public Byte getStatus() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>lesson.sys_notice.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lesson.sys_notice.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>lesson.sys_notice.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>lesson.sys_notice.created_by</code>. 创建人ID
     */
    public void setCreatedBy(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.created_by</code>. 创建人ID
     */
    public Long getCreatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>lesson.sys_notice.updated_by</code>. 更新人ID
     */
    public void setUpdatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.updated_by</code>. 更新人ID
     */
    public Long getUpdatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>lesson.sys_notice.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setIsDeleted(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.sys_notice.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getIsDeleted() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, Byte, String, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysNotice.SYS_NOTICE.ID;
    }

    @Override
    public Field<String> field2() {
        return SysNotice.SYS_NOTICE.NOTICE_TITLE;
    }

    @Override
    public Field<Byte> field3() {
        return SysNotice.SYS_NOTICE.NOTICE_TYPE;
    }

    @Override
    public Field<String> field4() {
        return SysNotice.SYS_NOTICE.NOTICE_CONTENT;
    }

    @Override
    public Field<Byte> field5() {
        return SysNotice.SYS_NOTICE.STATUS;
    }

    @Override
    public Field<String> field6() {
        return SysNotice.SYS_NOTICE.REMARK;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SysNotice.SYS_NOTICE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return SysNotice.SYS_NOTICE.UPDATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return SysNotice.SYS_NOTICE.CREATED_BY;
    }

    @Override
    public Field<Long> field10() {
        return SysNotice.SYS_NOTICE.UPDATED_BY;
    }

    @Override
    public Field<Byte> field11() {
        return SysNotice.SYS_NOTICE.IS_DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNoticeTitle();
    }

    @Override
    public Byte component3() {
        return getNoticeType();
    }

    @Override
    public String component4() {
        return getNoticeContent();
    }

    @Override
    public Byte component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getRemark();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Long component9() {
        return getCreatedBy();
    }

    @Override
    public Long component10() {
        return getUpdatedBy();
    }

    @Override
    public Byte component11() {
        return getIsDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNoticeTitle();
    }

    @Override
    public Byte value3() {
        return getNoticeType();
    }

    @Override
    public String value4() {
        return getNoticeContent();
    }

    @Override
    public Byte value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getRemark();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public Long value9() {
        return getCreatedBy();
    }

    @Override
    public Long value10() {
        return getUpdatedBy();
    }

    @Override
    public Byte value11() {
        return getIsDeleted();
    }

    @Override
    public SysNoticeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysNoticeRecord value2(String value) {
        setNoticeTitle(value);
        return this;
    }

    @Override
    public SysNoticeRecord value3(Byte value) {
        setNoticeType(value);
        return this;
    }

    @Override
    public SysNoticeRecord value4(String value) {
        setNoticeContent(value);
        return this;
    }

    @Override
    public SysNoticeRecord value5(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysNoticeRecord value6(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public SysNoticeRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SysNoticeRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SysNoticeRecord value9(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SysNoticeRecord value10(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public SysNoticeRecord value11(Byte value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SysNoticeRecord values(Long value1, String value2, Byte value3, String value4, Byte value5, String value6, LocalDateTime value7, LocalDateTime value8, Long value9, Long value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysNoticeRecord
     */
    public SysNoticeRecord() {
        super(SysNotice.SYS_NOTICE);
    }

    /**
     * Create a detached, initialised SysNoticeRecord
     */
    public SysNoticeRecord(Long id, String noticeTitle, Byte noticeType, String noticeContent, Byte status, String remark, LocalDateTime createdAt, LocalDateTime updatedAt, Long createdBy, Long updatedBy, Byte isDeleted) {
        super(SysNotice.SYS_NOTICE);

        setId(id);
        setNoticeTitle(noticeTitle);
        setNoticeType(noticeType);
        setNoticeContent(noticeContent);
        setStatus(status);
        setRemark(remark);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setIsDeleted(isDeleted);
    }
}
