/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables.records;


import com.lesson.repository.tables.SysPermission;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统权限表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionRecord extends UpdatableRecordImpl<SysPermissionRecord> implements Record12<Long, Long, String, Byte, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson.sys_permission.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson.sys_permission.parent_id</code>. 父权限ID
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.parent_id</code>. 父权限ID
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson.sys_permission.permission_name</code>. 权限名称
     */
    public void setPermissionName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.permission_name</code>. 权限名称
     */
    public String getPermissionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lesson.sys_permission.permission_type</code>. 权限类型：1-菜单，2-按钮，3-接口
     */
    public void setPermissionType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.permission_type</code>. 权限类型：1-菜单，2-按钮，3-接口
     */
    public Byte getPermissionType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>lesson.sys_permission.path</code>. 路径
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.path</code>. 路径
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lesson.sys_permission.component</code>. 前端组件
     */
    public void setComponent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.component</code>. 前端组件
     */
    public String getComponent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lesson.sys_permission.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lesson.sys_permission.sort</code>. 排序
     */
    public void setSort(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.sort</code>. 排序
     */
    public Integer getSort() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>lesson.sys_permission.status</code>. 状态：0-禁用，1-启用
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.status</code>. 状态：0-禁用，1-启用
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>lesson.sys_permission.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>lesson.sys_permission.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>lesson.sys_permission.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setDeleted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>lesson.sys_permission.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Byte getDeleted() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, String, Byte, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, String, Byte, String, String, String, Integer, Byte, LocalDateTime, LocalDateTime, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysPermission.SYS_PERMISSION.ID;
    }

    @Override
    public Field<Long> field2() {
        return SysPermission.SYS_PERMISSION.PARENT_ID;
    }

    @Override
    public Field<String> field3() {
        return SysPermission.SYS_PERMISSION.PERMISSION_NAME;
    }

    @Override
    public Field<Byte> field4() {
        return SysPermission.SYS_PERMISSION.PERMISSION_TYPE;
    }

    @Override
    public Field<String> field5() {
        return SysPermission.SYS_PERMISSION.PATH;
    }

    @Override
    public Field<String> field6() {
        return SysPermission.SYS_PERMISSION.COMPONENT;
    }

    @Override
    public Field<String> field7() {
        return SysPermission.SYS_PERMISSION.ICON;
    }

    @Override
    public Field<Integer> field8() {
        return SysPermission.SYS_PERMISSION.SORT;
    }

    @Override
    public Field<Byte> field9() {
        return SysPermission.SYS_PERMISSION.STATUS;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SysPermission.SYS_PERMISSION.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return SysPermission.SYS_PERMISSION.UPDATE_TIME;
    }

    @Override
    public Field<Byte> field12() {
        return SysPermission.SYS_PERMISSION.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getParentId();
    }

    @Override
    public String component3() {
        return getPermissionName();
    }

    @Override
    public Byte component4() {
        return getPermissionType();
    }

    @Override
    public String component5() {
        return getPath();
    }

    @Override
    public String component6() {
        return getComponent();
    }

    @Override
    public String component7() {
        return getIcon();
    }

    @Override
    public Integer component8() {
        return getSort();
    }

    @Override
    public Byte component9() {
        return getStatus();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    @Override
    public Byte component12() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getParentId();
    }

    @Override
    public String value3() {
        return getPermissionName();
    }

    @Override
    public Byte value4() {
        return getPermissionType();
    }

    @Override
    public String value5() {
        return getPath();
    }

    @Override
    public String value6() {
        return getComponent();
    }

    @Override
    public String value7() {
        return getIcon();
    }

    @Override
    public Integer value8() {
        return getSort();
    }

    @Override
    public Byte value9() {
        return getStatus();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    @Override
    public Byte value12() {
        return getDeleted();
    }

    @Override
    public SysPermissionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysPermissionRecord value2(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public SysPermissionRecord value3(String value) {
        setPermissionName(value);
        return this;
    }

    @Override
    public SysPermissionRecord value4(Byte value) {
        setPermissionType(value);
        return this;
    }

    @Override
    public SysPermissionRecord value5(String value) {
        setPath(value);
        return this;
    }

    @Override
    public SysPermissionRecord value6(String value) {
        setComponent(value);
        return this;
    }

    @Override
    public SysPermissionRecord value7(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public SysPermissionRecord value8(Integer value) {
        setSort(value);
        return this;
    }

    @Override
    public SysPermissionRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public SysPermissionRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SysPermissionRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SysPermissionRecord value12(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public SysPermissionRecord values(Long value1, Long value2, String value3, Byte value4, String value5, String value6, String value7, Integer value8, Byte value9, LocalDateTime value10, LocalDateTime value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysPermissionRecord
     */
    public SysPermissionRecord() {
        super(SysPermission.SYS_PERMISSION);
    }

    /**
     * Create a detached, initialised SysPermissionRecord
     */
    public SysPermissionRecord(Long id, Long parentId, String permissionName, Byte permissionType, String path, String component, String icon, Integer sort, Byte status, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(SysPermission.SYS_PERMISSION);

        setId(id);
        setParentId(parentId);
        setPermissionName(permissionName);
        setPermissionType(permissionType);
        setPath(path);
        setComponent(component);
        setIcon(icon);
        setSort(sort);
        setStatus(status);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
    }
}
