package com.lesson.repository.tables.records;

import com.lesson.repository.tables.SysUserRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleRecord extends UpdatableRecordImpl<SysUserRoleRecord> implements Record6<Long, Long, Long, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lesson_prod.sys_user_role.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lesson_prod.sys_user_role.user_id</code>. 用户ID
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.user_id</code>. 用户ID
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>lesson_prod.sys_user_role.role_id</code>. 角色ID
     */
    public void setRoleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>lesson_prod.sys_user_role.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>lesson_prod.sys_user_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>lesson_prod.sys_user_role.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public void setDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>lesson_prod.sys_user_role.deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public Integer getDeleted() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SysUserRole.SYS_USER_ROLE.ID;
    }

    @Override
    public Field<Long> field2() {
        return SysUserRole.SYS_USER_ROLE.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return SysUserRole.SYS_USER_ROLE.ROLE_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return SysUserRole.SYS_USER_ROLE.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SysUserRole.SYS_USER_ROLE.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field6() {
        return SysUserRole.SYS_USER_ROLE.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public Integer component6() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getRoleId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public Integer value6() {
        return getDeleted();
    }

    @Override
    public SysUserRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value3(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public SysUserRoleRecord value6(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public SysUserRoleRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRoleRecord
     */
    public SysUserRoleRecord() {
        super(SysUserRole.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised SysUserRoleRecord
     */
    public SysUserRoleRecord(Long id, Long userId, Long roleId, LocalDateTime createdTime, LocalDateTime updateTime, Integer deleted) {
        super(SysUserRole.SYS_USER_ROLE);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setCreatedTime(createdTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
    }
} 