server:
  servlet:
    context-path: /lesson

logging:
  level:
    root: INFO
    com.lesson: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.jooq: DEBUG
