/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository;


import com.lesson.repository.tables.EduAttendance;
import com.lesson.repository.tables.EduCampus;
import com.lesson.repository.tables.EduClass;
import com.lesson.repository.tables.EduClassCoach;
import com.lesson.repository.tables.EduClassStudent;
import com.lesson.repository.tables.EduClassroom;
import com.lesson.repository.tables.EduCoach;
import com.lesson.repository.tables.EduCoachQualification;
import com.lesson.repository.tables.EduCourse;
import com.lesson.repository.tables.EduCourseCategory;
import com.lesson.repository.tables.EduCourseChapter;
import com.lesson.repository.tables.EduCourseLesson;
import com.lesson.repository.tables.EduDashboard;
import com.lesson.repository.tables.EduDataExport;
import com.lesson.repository.tables.EduExpense;
import com.lesson.repository.tables.EduExpenseType;
import com.lesson.repository.tables.EduInstitution;
import com.lesson.repository.tables.EduInvoice;
import com.lesson.repository.tables.EduPayment;
import com.lesson.repository.tables.EduSchedule;
import com.lesson.repository.tables.EduStatisticsReport;
import com.lesson.repository.tables.EduStudent;
import com.lesson.repository.tables.SysConfig;
import com.lesson.repository.tables.SysDictData;
import com.lesson.repository.tables.SysDictType;
import com.lesson.repository.tables.SysLog;
import com.lesson.repository.tables.SysLoginLog;
import com.lesson.repository.tables.SysNotice;
import com.lesson.repository.tables.SysOperationLog;
import com.lesson.repository.tables.SysPermission;
import com.lesson.repository.tables.SysRole;
import com.lesson.repository.tables.SysRolePermission;
import com.lesson.repository.tables.SysUser;
import com.lesson.repository.tables.SysUserRole;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in lesson.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EDU_CLASS_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.CAMPUS_ID }, false);
    public static final Index EDU_CLASSROOM_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduClassroom.EDU_CLASSROOM, new OrderField[] { EduClassroom.EDU_CLASSROOM.CAMPUS_ID }, false);
    public static final Index EDU_COACH_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.CAMPUS_ID }, false);
    public static final Index EDU_COURSE_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduCourse.EDU_COURSE, new OrderField[] { EduCourse.EDU_COURSE.CAMPUS_ID }, false);
    public static final Index EDU_EXPENSE_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.CAMPUS_ID }, false);
    public static final Index EDU_STUDENT_IDX_CAMPUS_ID = Internal.createIndex(DSL.name("idx_campus_id"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.CAMPUS_ID }, false);
    public static final Index EDU_COURSE_IDX_CATEGORY_ID = Internal.createIndex(DSL.name("idx_category_id"), EduCourse.EDU_COURSE, new OrderField[] { EduCourse.EDU_COURSE.CATEGORY_ID }, false);
    public static final Index EDU_COURSE_LESSON_IDX_CHAPTER_ID = Internal.createIndex(DSL.name("idx_chapter_id"), EduCourseLesson.EDU_COURSE_LESSON, new OrderField[] { EduCourseLesson.EDU_COURSE_LESSON.CHAPTER_ID }, false);
    public static final Index EDU_ATTENDANCE_IDX_CHECK_IN_TIME = Internal.createIndex(DSL.name("idx_check_in_time"), EduAttendance.EDU_ATTENDANCE, new OrderField[] { EduAttendance.EDU_ATTENDANCE.CHECK_IN_TIME }, false);
    public static final Index EDU_CLASS_COACH_IDX_CLASS_ID = Internal.createIndex(DSL.name("idx_class_id"), EduClassCoach.EDU_CLASS_COACH, new OrderField[] { EduClassCoach.EDU_CLASS_COACH.CLASS_ID }, false);
    public static final Index EDU_CLASS_STUDENT_IDX_CLASS_ID = Internal.createIndex(DSL.name("idx_class_id"), EduClassStudent.EDU_CLASS_STUDENT, new OrderField[] { EduClassStudent.EDU_CLASS_STUDENT.CLASS_ID }, false);
    public static final Index EDU_PAYMENT_IDX_CLASS_ID = Internal.createIndex(DSL.name("idx_class_id"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.CLASS_ID }, false);
    public static final Index EDU_SCHEDULE_IDX_CLASS_ID = Internal.createIndex(DSL.name("idx_class_id"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.CLASS_ID }, false);
    public static final Index EDU_SCHEDULE_IDX_CLASSROOM_ID = Internal.createIndex(DSL.name("idx_classroom_id"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.CLASSROOM_ID }, false);
    public static final Index EDU_CLASS_IDX_COACH_ID = Internal.createIndex(DSL.name("idx_coach_id"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.COACH_ID }, false);
    public static final Index EDU_CLASS_COACH_IDX_COACH_ID = Internal.createIndex(DSL.name("idx_coach_id"), EduClassCoach.EDU_CLASS_COACH, new OrderField[] { EduClassCoach.EDU_CLASS_COACH.COACH_ID }, false);
    public static final Index EDU_COACH_QUALIFICATION_IDX_COACH_ID = Internal.createIndex(DSL.name("idx_coach_id"), EduCoachQualification.EDU_COACH_QUALIFICATION, new OrderField[] { EduCoachQualification.EDU_COACH_QUALIFICATION.COACH_ID }, false);
    public static final Index EDU_SCHEDULE_IDX_COACH_ID = Internal.createIndex(DSL.name("idx_coach_id"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.COACH_ID }, false);
    public static final Index SYS_CONFIG_IDX_CONFIG_TYPE = Internal.createIndex(DSL.name("idx_config_type"), SysConfig.SYS_CONFIG, new OrderField[] { SysConfig.SYS_CONFIG.CONFIG_TYPE }, false);
    public static final Index EDU_CLASS_IDX_COURSE_ID = Internal.createIndex(DSL.name("idx_course_id"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.COURSE_ID }, false);
    public static final Index EDU_COURSE_CHAPTER_IDX_COURSE_ID = Internal.createIndex(DSL.name("idx_course_id"), EduCourseChapter.EDU_COURSE_CHAPTER, new OrderField[] { EduCourseChapter.EDU_COURSE_CHAPTER.COURSE_ID }, false);
    public static final Index EDU_COURSE_LESSON_IDX_COURSE_ID = Internal.createIndex(DSL.name("idx_course_id"), EduCourseLesson.EDU_COURSE_LESSON, new OrderField[] { EduCourseLesson.EDU_COURSE_LESSON.COURSE_ID }, false);
    public static final Index EDU_PAYMENT_IDX_COURSE_ID = Internal.createIndex(DSL.name("idx_course_id"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.COURSE_ID }, false);
    public static final Index EDU_ATTENDANCE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduAttendance.EDU_ATTENDANCE, new OrderField[] { EduAttendance.EDU_ATTENDANCE.CREATED_AT }, false);
    public static final Index EDU_CAMPUS_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCampus.EDU_CAMPUS, new OrderField[] { EduCampus.EDU_CAMPUS.CREATED_AT }, false);
    public static final Index EDU_CLASS_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.CREATED_AT }, false);
    public static final Index EDU_CLASSROOM_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduClassroom.EDU_CLASSROOM, new OrderField[] { EduClassroom.EDU_CLASSROOM.CREATED_AT }, false);
    public static final Index EDU_CLASS_COACH_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduClassCoach.EDU_CLASS_COACH, new OrderField[] { EduClassCoach.EDU_CLASS_COACH.CREATED_AT }, false);
    public static final Index EDU_CLASS_STUDENT_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduClassStudent.EDU_CLASS_STUDENT, new OrderField[] { EduClassStudent.EDU_CLASS_STUDENT.CREATED_AT }, false);
    public static final Index EDU_COACH_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.CREATED_AT }, false);
    public static final Index EDU_COACH_QUALIFICATION_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCoachQualification.EDU_COACH_QUALIFICATION, new OrderField[] { EduCoachQualification.EDU_COACH_QUALIFICATION.CREATED_AT }, false);
    public static final Index EDU_COURSE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCourse.EDU_COURSE, new OrderField[] { EduCourse.EDU_COURSE.CREATED_AT }, false);
    public static final Index EDU_COURSE_CATEGORY_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCourseCategory.EDU_COURSE_CATEGORY, new OrderField[] { EduCourseCategory.EDU_COURSE_CATEGORY.CREATED_AT }, false);
    public static final Index EDU_COURSE_CHAPTER_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCourseChapter.EDU_COURSE_CHAPTER, new OrderField[] { EduCourseChapter.EDU_COURSE_CHAPTER.CREATED_AT }, false);
    public static final Index EDU_COURSE_LESSON_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduCourseLesson.EDU_COURSE_LESSON, new OrderField[] { EduCourseLesson.EDU_COURSE_LESSON.CREATED_AT }, false);
    public static final Index EDU_DASHBOARD_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduDashboard.EDU_DASHBOARD, new OrderField[] { EduDashboard.EDU_DASHBOARD.CREATED_AT }, false);
    public static final Index EDU_DATA_EXPORT_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduDataExport.EDU_DATA_EXPORT, new OrderField[] { EduDataExport.EDU_DATA_EXPORT.CREATED_AT }, false);
    public static final Index EDU_EXPENSE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.CREATED_AT }, false);
    public static final Index EDU_EXPENSE_TYPE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduExpenseType.EDU_EXPENSE_TYPE, new OrderField[] { EduExpenseType.EDU_EXPENSE_TYPE.CREATED_AT }, false);
    public static final Index EDU_INSTITUTION_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduInstitution.EDU_INSTITUTION, new OrderField[] { EduInstitution.EDU_INSTITUTION.CREATED_AT }, false);
    public static final Index EDU_INVOICE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduInvoice.EDU_INVOICE, new OrderField[] { EduInvoice.EDU_INVOICE.CREATED_AT }, false);
    public static final Index EDU_PAYMENT_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.CREATED_AT }, false);
    public static final Index EDU_SCHEDULE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.CREATED_AT }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.CREATED_AT }, false);
    public static final Index EDU_STUDENT_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.CREATED_AT }, false);
    public static final Index SYS_CONFIG_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysConfig.SYS_CONFIG, new OrderField[] { SysConfig.SYS_CONFIG.CREATED_AT }, false);
    public static final Index SYS_DICT_DATA_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysDictData.SYS_DICT_DATA, new OrderField[] { SysDictData.SYS_DICT_DATA.CREATED_AT }, false);
    public static final Index SYS_DICT_TYPE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysDictType.SYS_DICT_TYPE, new OrderField[] { SysDictType.SYS_DICT_TYPE.CREATED_AT }, false);
    public static final Index SYS_LOG_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.CREATED_AT }, false);
    public static final Index SYS_LOGIN_LOG_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysLoginLog.SYS_LOGIN_LOG, new OrderField[] { SysLoginLog.SYS_LOGIN_LOG.CREATED_AT }, false);
    public static final Index SYS_NOTICE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysNotice.SYS_NOTICE, new OrderField[] { SysNotice.SYS_NOTICE.CREATED_AT }, false);
    public static final Index SYS_OPERATION_LOG_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysOperationLog.SYS_OPERATION_LOG, new OrderField[] { SysOperationLog.SYS_OPERATION_LOG.CREATED_AT }, false);
    public static final Index SYS_PERMISSION_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysPermission.SYS_PERMISSION, new OrderField[] { SysPermission.SYS_PERMISSION.CREATED_AT }, false);
    public static final Index SYS_ROLE_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.CREATED_AT }, false);
    public static final Index SYS_USER_IDX_CREATED_AT = Internal.createIndex(DSL.name("idx_created_at"), SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.CREATED_AT }, false);
    public static final Index EDU_DASHBOARD_IDX_DASHBOARD_TYPE = Internal.createIndex(DSL.name("idx_dashboard_type"), EduDashboard.EDU_DASHBOARD, new OrderField[] { EduDashboard.EDU_DASHBOARD.DASHBOARD_TYPE }, false);
    public static final Index SYS_DICT_DATA_IDX_DICT_SORT = Internal.createIndex(DSL.name("idx_dict_sort"), SysDictData.SYS_DICT_DATA, new OrderField[] { SysDictData.SYS_DICT_DATA.DICT_SORT }, false);
    public static final Index SYS_DICT_DATA_IDX_DICT_TYPE = Internal.createIndex(DSL.name("idx_dict_type"), SysDictData.SYS_DICT_DATA, new OrderField[] { SysDictData.SYS_DICT_DATA.DICT_TYPE }, false);
    public static final Index SYS_USER_IDX_EMAIL = Internal.createIndex(DSL.name("idx_email"), SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.EMAIL }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_END_DATE = Internal.createIndex(DSL.name("idx_end_date"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.END_DATE }, false);
    public static final Index EDU_SCHEDULE_IDX_END_TIME = Internal.createIndex(DSL.name("idx_end_time"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.END_TIME }, false);
    public static final Index EDU_EXPENSE_IDX_EXPENSE_DATE = Internal.createIndex(DSL.name("idx_expense_date"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.EXPENSE_DATE }, false);
    public static final Index EDU_EXPENSE_IDX_EXPENSE_TYPE_ID = Internal.createIndex(DSL.name("idx_expense_type_id"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.EXPENSE_TYPE_ID }, false);
    public static final Index EDU_DATA_EXPORT_IDX_EXPORT_TYPE = Internal.createIndex(DSL.name("idx_export_type"), EduDataExport.EDU_DATA_EXPORT, new OrderField[] { EduDataExport.EDU_DATA_EXPORT.EXPORT_TYPE }, false);
    public static final Index EDU_CAMPUS_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduCampus.EDU_CAMPUS, new OrderField[] { EduCampus.EDU_CAMPUS.INSTITUTION_ID }, false);
    public static final Index EDU_CLASS_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.INSTITUTION_ID }, false);
    public static final Index EDU_COACH_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.INSTITUTION_ID }, false);
    public static final Index EDU_COURSE_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduCourse.EDU_COURSE, new OrderField[] { EduCourse.EDU_COURSE.INSTITUTION_ID }, false);
    public static final Index EDU_DASHBOARD_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduDashboard.EDU_DASHBOARD, new OrderField[] { EduDashboard.EDU_DASHBOARD.INSTITUTION_ID }, false);
    public static final Index EDU_DATA_EXPORT_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduDataExport.EDU_DATA_EXPORT, new OrderField[] { EduDataExport.EDU_DATA_EXPORT.INSTITUTION_ID }, false);
    public static final Index EDU_EXPENSE_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.INSTITUTION_ID }, false);
    public static final Index EDU_PAYMENT_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.INSTITUTION_ID }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.INSTITUTION_ID }, false);
    public static final Index EDU_STUDENT_IDX_INSTITUTION_ID = Internal.createIndex(DSL.name("idx_institution_id"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.INSTITUTION_ID }, false);
    public static final Index EDU_INVOICE_IDX_INVOICE_CODE = Internal.createIndex(DSL.name("idx_invoice_code"), EduInvoice.EDU_INVOICE, new OrderField[] { EduInvoice.EDU_INVOICE.INVOICE_CODE }, false);
    public static final Index EDU_INVOICE_IDX_INVOICE_NO = Internal.createIndex(DSL.name("idx_invoice_no"), EduInvoice.EDU_INVOICE, new OrderField[] { EduInvoice.EDU_INVOICE.INVOICE_NO }, false);
    public static final Index EDU_INVOICE_IDX_ISSUE_DATE = Internal.createIndex(DSL.name("idx_issue_date"), EduInvoice.EDU_INVOICE, new OrderField[] { EduInvoice.EDU_INVOICE.ISSUE_DATE }, false);
    public static final Index EDU_SCHEDULE_IDX_LESSON_ID = Internal.createIndex(DSL.name("idx_lesson_id"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.LESSON_ID }, false);
    public static final Index EDU_CAMPUS_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduCampus.EDU_CAMPUS, new OrderField[] { EduCampus.EDU_CAMPUS.NAME }, false);
    public static final Index EDU_CLASS_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduClass.EDU_CLASS, new OrderField[] { EduClass.EDU_CLASS.NAME }, false);
    public static final Index EDU_CLASSROOM_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduClassroom.EDU_CLASSROOM, new OrderField[] { EduClassroom.EDU_CLASSROOM.NAME }, false);
    public static final Index EDU_COACH_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.NAME }, false);
    public static final Index EDU_COURSE_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduCourse.EDU_COURSE, new OrderField[] { EduCourse.EDU_COURSE.NAME }, false);
    public static final Index EDU_INSTITUTION_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduInstitution.EDU_INSTITUTION, new OrderField[] { EduInstitution.EDU_INSTITUTION.NAME }, false);
    public static final Index EDU_STUDENT_IDX_NAME = Internal.createIndex(DSL.name("idx_name"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.NAME }, false);
    public static final Index SYS_NOTICE_IDX_NOTICE_TYPE = Internal.createIndex(DSL.name("idx_notice_type"), SysNotice.SYS_NOTICE, new OrderField[] { SysNotice.SYS_NOTICE.NOTICE_TYPE }, false);
    public static final Index SYS_LOG_IDX_OPERATION = Internal.createIndex(DSL.name("idx_operation"), SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.OPERATION }, false);
    public static final Index EDU_COURSE_CATEGORY_IDX_PARENT_ID = Internal.createIndex(DSL.name("idx_parent_id"), EduCourseCategory.EDU_COURSE_CATEGORY, new OrderField[] { EduCourseCategory.EDU_COURSE_CATEGORY.PARENT_ID }, false);
    public static final Index SYS_PERMISSION_IDX_PARENT_ID = Internal.createIndex(DSL.name("idx_parent_id"), SysPermission.SYS_PERMISSION, new OrderField[] { SysPermission.SYS_PERMISSION.PARENT_ID }, false);
    public static final Index EDU_STUDENT_IDX_PARENT_PHONE = Internal.createIndex(DSL.name("idx_parent_phone"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.PARENT_PHONE }, false);
    public static final Index EDU_EXPENSE_IDX_PAYMENT_STATUS = Internal.createIndex(DSL.name("idx_payment_status"), EduExpense.EDU_EXPENSE, new OrderField[] { EduExpense.EDU_EXPENSE.PAYMENT_STATUS }, false);
    public static final Index EDU_PAYMENT_IDX_PAYMENT_STATUS = Internal.createIndex(DSL.name("idx_payment_status"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.PAYMENT_STATUS }, false);
    public static final Index EDU_PAYMENT_IDX_PAYMENT_TIME = Internal.createIndex(DSL.name("idx_payment_time"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.PAYMENT_TIME }, false);
    public static final Index SYS_ROLE_PERMISSION_IDX_PERMISSION_ID = Internal.createIndex(DSL.name("idx_permission_id"), SysRolePermission.SYS_ROLE_PERMISSION, new OrderField[] { SysRolePermission.SYS_ROLE_PERMISSION.PERMISSION_ID }, false);
    public static final Index EDU_COACH_IDX_PHONE = Internal.createIndex(DSL.name("idx_phone"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.PHONE }, false);
    public static final Index EDU_STUDENT_IDX_PHONE = Internal.createIndex(DSL.name("idx_phone"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.PHONE }, false);
    public static final Index SYS_USER_IDX_PHONE = Internal.createIndex(DSL.name("idx_phone"), SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.PHONE }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_REPORT_PERIOD = Internal.createIndex(DSL.name("idx_report_period"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.REPORT_PERIOD }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_REPORT_TYPE = Internal.createIndex(DSL.name("idx_report_type"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.REPORT_TYPE }, false);
    public static final Index SYS_ROLE_PERMISSION_IDX_ROLE_ID = Internal.createIndex(DSL.name("idx_role_id"), SysRolePermission.SYS_ROLE_PERMISSION, new OrderField[] { SysRolePermission.SYS_ROLE_PERMISSION.ROLE_ID }, false);
    public static final Index SYS_USER_ROLE_IDX_ROLE_ID = Internal.createIndex(DSL.name("idx_role_id"), SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ROLE_ID }, false);
    public static final Index EDU_ATTENDANCE_IDX_SCHEDULE_ID = Internal.createIndex(DSL.name("idx_schedule_id"), EduAttendance.EDU_ATTENDANCE, new OrderField[] { EduAttendance.EDU_ATTENDANCE.SCHEDULE_ID }, false);
    public static final Index EDU_STATISTICS_REPORT_IDX_START_DATE = Internal.createIndex(DSL.name("idx_start_date"), EduStatisticsReport.EDU_STATISTICS_REPORT, new OrderField[] { EduStatisticsReport.EDU_STATISTICS_REPORT.START_DATE }, false);
    public static final Index EDU_SCHEDULE_IDX_START_TIME = Internal.createIndex(DSL.name("idx_start_time"), EduSchedule.EDU_SCHEDULE, new OrderField[] { EduSchedule.EDU_SCHEDULE.START_TIME }, false);
    public static final Index EDU_DATA_EXPORT_IDX_STATUS = Internal.createIndex(DSL.name("idx_status"), EduDataExport.EDU_DATA_EXPORT, new OrderField[] { EduDataExport.EDU_DATA_EXPORT.STATUS }, false);
    public static final Index SYS_LOG_IDX_STATUS = Internal.createIndex(DSL.name("idx_status"), SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.STATUS }, false);
    public static final Index SYS_NOTICE_IDX_STATUS = Internal.createIndex(DSL.name("idx_status"), SysNotice.SYS_NOTICE, new OrderField[] { SysNotice.SYS_NOTICE.STATUS }, false);
    public static final Index EDU_ATTENDANCE_IDX_STUDENT_ID = Internal.createIndex(DSL.name("idx_student_id"), EduAttendance.EDU_ATTENDANCE, new OrderField[] { EduAttendance.EDU_ATTENDANCE.STUDENT_ID }, false);
    public static final Index EDU_CLASS_STUDENT_IDX_STUDENT_ID = Internal.createIndex(DSL.name("idx_student_id"), EduClassStudent.EDU_CLASS_STUDENT, new OrderField[] { EduClassStudent.EDU_CLASS_STUDENT.STUDENT_ID }, false);
    public static final Index EDU_PAYMENT_IDX_STUDENT_ID = Internal.createIndex(DSL.name("idx_student_id"), EduPayment.EDU_PAYMENT, new OrderField[] { EduPayment.EDU_PAYMENT.STUDENT_ID }, false);
    public static final Index EDU_COACH_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), EduCoach.EDU_COACH, new OrderField[] { EduCoach.EDU_COACH.USER_ID }, false);
    public static final Index EDU_STUDENT_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), EduStudent.EDU_STUDENT, new OrderField[] { EduStudent.EDU_STUDENT.USER_ID }, false);
    public static final Index SYS_LOG_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.USER_ID }, false);
    public static final Index SYS_OPERATION_LOG_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), SysOperationLog.SYS_OPERATION_LOG, new OrderField[] { SysOperationLog.SYS_OPERATION_LOG.USER_ID }, false);
    public static final Index SYS_USER_ROLE_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.USER_ID }, false);
    public static final Index SYS_LOG_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.USERNAME }, false);
    public static final Index SYS_LOGIN_LOG_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), SysLoginLog.SYS_LOGIN_LOG, new OrderField[] { SysLoginLog.SYS_LOGIN_LOG.USERNAME }, false);
    public static final Index SYS_OPERATION_LOG_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), SysOperationLog.SYS_OPERATION_LOG, new OrderField[] { SysOperationLog.SYS_OPERATION_LOG.USERNAME }, false);
}
