-- 机构表
CREATE TABLE IF NOT EXISTS `edu_institution` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(100) NOT NULL COMMENT '机构名称',
    `code` VARCHAR(50) NOT NULL COMMENT '机构编码',
    `logo` VARCHAR(255) COMMENT '机构logo',
    `address` VARCHAR(255) COMMENT '机构地址',
    `contact_name` VARCHAR(50) COMMENT '联系人姓名',
    `contact_phone` VARCHAR(20) COMMENT '联系人电话',
    `contact_email` VARCHAR(100) COMMENT '联系人邮箱',
    `description` TEXT COMMENT '机构描述',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by` BIGINT COMMENT '创建人ID',
    `updated_by` BIGINT COMMENT '更新人ID',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    KEY `idx_name` (`name`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教育机构表';

-- 校区表
CREATE TABLE IF NOT EXISTS `edu_campus` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `institution_id` BIGINT NOT NULL COMMENT '所属机构ID',
    `name` VARCHAR(100) NOT NULL COMMENT '校区名称',
    `code` VARCHAR(50) NOT NULL COMMENT '校区编码',
    `address` VARCHAR(255) COMMENT '校区地址',
    `area` DECIMAL(10,2) COMMENT '校区面积(平方米)',
    `contact_name` VARCHAR(50) COMMENT '联系人姓名',
    `contact_phone` VARCHAR(20) COMMENT '联系人电话',
    `description` TEXT COMMENT '校区描述',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by` BIGINT COMMENT '创建人ID',
    `updated_by` BIGINT COMMENT '更新人ID',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    KEY `idx_institution_id` (`institution_id`),
    KEY `idx_name` (`name`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='校区表';

-- 教练表
CREATE TABLE IF NOT EXISTS `edu_coach` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `institution_id` BIGINT NOT NULL COMMENT '所属机构ID',
    `campus_id` BIGINT COMMENT '所属校区ID',
    `user_id` BIGINT COMMENT '关联用户ID',
    `name` VARCHAR(50) NOT NULL COMMENT '教练姓名',
    `code` VARCHAR(50) NOT NULL COMMENT '教练编码',
    `gender` TINYINT COMMENT '性别：0-未知，1-男，2-女',
    `birthday` DATE COMMENT '出生日期',
    `id_card` VARCHAR(18) COMMENT '身份证号',
    `phone` VARCHAR(20) COMMENT '手机号',
    `email` VARCHAR(100) COMMENT '邮箱',
    `avatar` VARCHAR(255) COMMENT '头像URL',
    `education` VARCHAR(50) COMMENT '学历',
    `specialty` VARCHAR(255) COMMENT '专长',
    `introduction` TEXT COMMENT '个人介绍',
    `entry_date` DATE COMMENT '入职日期',
    `leave_date` DATE COMMENT '离职日期',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by` BIGINT COMMENT '创建人ID',
    `updated_by` BIGINT COMMENT '更新人ID',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    KEY `idx_institution_id` (`institution_id`),
    KEY `idx_campus_id` (`campus_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_name` (`name`),
    KEY `idx_phone` (`phone`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教练表';

-- 教练资质表
CREATE TABLE IF NOT EXISTS `edu_coach_qualification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `coach_id` BIGINT NOT NULL COMMENT '教练ID',
    `name` VARCHAR(100) NOT NULL COMMENT '资质名称',
    `code` VARCHAR(50) COMMENT '资质编号',
    `issue_date` DATE COMMENT '发证日期',
    `expire_date` DATE COMMENT '过期日期',
    `issuing_authority` VARCHAR(100) COMMENT '发证机构',
    `description` TEXT COMMENT '描述',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by` BIGINT COMMENT '创建人ID',
    `updated_by` BIGINT COMMENT '更新人ID',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_coach_id` (`coach_id`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教练资质表'; 