/*
 * This file is generated by jOOQ.
 */
package com.lesson.repository.tables;


import com.lesson.repository.Indexes;
import com.lesson.repository.Keys;
import com.lesson.repository.Lesson;
import com.lesson.repository.tables.records.SysDictDataRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 字典数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictData extends TableImpl<SysDictDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lesson.sys_dict_data</code>
     */
    public static final SysDictData SYS_DICT_DATA = new SysDictData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysDictDataRecord> getRecordType() {
        return SysDictDataRecord.class;
    }

    /**
     * The column <code>lesson.sys_dict_data.id</code>. 主键ID
     */
    public final TableField<SysDictDataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>lesson.sys_dict_data.dict_type</code>. 字典类型
     */
    public final TableField<SysDictDataRecord, String> DICT_TYPE = createField(DSL.name("dict_type"), SQLDataType.VARCHAR(100).nullable(false), this, "字典类型");

    /**
     * The column <code>lesson.sys_dict_data.dict_label</code>. 字典标签
     */
    public final TableField<SysDictDataRecord, String> DICT_LABEL = createField(DSL.name("dict_label"), SQLDataType.VARCHAR(100).nullable(false), this, "字典标签");

    /**
     * The column <code>lesson.sys_dict_data.dict_value</code>. 字典键值
     */
    public final TableField<SysDictDataRecord, String> DICT_VALUE = createField(DSL.name("dict_value"), SQLDataType.VARCHAR(100).nullable(false), this, "字典键值");

    /**
     * The column <code>lesson.sys_dict_data.dict_sort</code>. 字典排序
     */
    public final TableField<SysDictDataRecord, Integer> DICT_SORT = createField(DSL.name("dict_sort"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "字典排序");

    /**
     * The column <code>lesson.sys_dict_data.status</code>. 状态：0-禁用，1-启用
     */
    public final TableField<SysDictDataRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "状态：0-禁用，1-启用");

    /**
     * The column <code>lesson.sys_dict_data.remark</code>. 备注
     */
    public final TableField<SysDictDataRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(255), this, "备注");

    /**
     * The column <code>lesson.sys_dict_data.created_at</code>. 创建时间
     */
    public final TableField<SysDictDataRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>lesson.sys_dict_data.updated_at</code>. 更新时间
     */
    public final TableField<SysDictDataRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>lesson.sys_dict_data.created_by</code>. 创建人ID
     */
    public final TableField<SysDictDataRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "创建人ID");

    /**
     * The column <code>lesson.sys_dict_data.updated_by</code>. 更新人ID
     */
    public final TableField<SysDictDataRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT, this, "更新人ID");

    /**
     * The column <code>lesson.sys_dict_data.is_deleted</code>. 是否删除：0-未删除，1-已删除
     */
    public final TableField<SysDictDataRecord, Byte> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "是否删除：0-未删除，1-已删除");

    private SysDictData(Name alias, Table<SysDictDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysDictData(Name alias, Table<SysDictDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("字典数据表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>lesson.sys_dict_data</code> table reference
     */
    public SysDictData(String alias) {
        this(DSL.name(alias), SYS_DICT_DATA);
    }

    /**
     * Create an aliased <code>lesson.sys_dict_data</code> table reference
     */
    public SysDictData(Name alias) {
        this(alias, SYS_DICT_DATA);
    }

    /**
     * Create a <code>lesson.sys_dict_data</code> table reference
     */
    public SysDictData() {
        this(DSL.name("sys_dict_data"), null);
    }

    public <O extends Record> SysDictData(Table<O> child, ForeignKey<O, SysDictDataRecord> key) {
        super(child, key, SYS_DICT_DATA);
    }

    @Override
    public Schema getSchema() {
        return Lesson.LESSON;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_DICT_DATA_IDX_CREATED_AT, Indexes.SYS_DICT_DATA_IDX_DICT_SORT, Indexes.SYS_DICT_DATA_IDX_DICT_TYPE);
    }

    @Override
    public Identity<SysDictDataRecord, Long> getIdentity() {
        return (Identity<SysDictDataRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SysDictDataRecord> getPrimaryKey() {
        return Keys.KEY_SYS_DICT_DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<SysDictDataRecord>> getKeys() {
        return Arrays.<UniqueKey<SysDictDataRecord>>asList(Keys.KEY_SYS_DICT_DATA_PRIMARY);
    }

    @Override
    public SysDictData as(String alias) {
        return new SysDictData(DSL.name(alias), this);
    }

    @Override
    public SysDictData as(Name alias) {
        return new SysDictData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysDictData rename(String name) {
        return new SysDictData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysDictData rename(Name name) {
        return new SysDictData(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, String, String, Integer, Byte, String, LocalDateTime, LocalDateTime, Long, Long, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
